### ISSUE TITLE
After Core update and HA core restart devices remain unavailable

### ISSUE THREAD

**Issue by JBakers** [Sholofly/lghorizon#90]
**Describe the bug**
After core update to 2024.1.3 the devices stay unavailable. I both have a Next (DCX960) and a Next mini (VIP5002W).

**To Reproduce**
Restart/update core

**Expected behavior**
Devices be available

**Screenshots**

**Version of the component**
0.5.4

**Logging**
Enable debug logging and add your log. DO NOT SHARE SENSITIVE DATA SUCH AS PASSWORDS AND ACCOUNT INFO!
You can enable logging by setting up the logging component in HA as follows:

debug log attached
[home-assistant.log](https://github.com/Sholofly/lghorizon/files/14000644/home-assistant.log)

**Additional context**
There is no log in HA as the integration loads without a problem, (see debuglog above)
Update to latest core 2024.1.5
I restarted HA multiple times, also restarted the container.
I removed integration completely and reinstalled.
Energy Modes are set to high and both Next boxes also rebooted.

**Comment by Sholofly** [comment]
Great Britain?

**Comment by JBakers** [comment]
Netherlands

**Comment by mtbbart** [comment]
Same behaviour in Belgium with Telenet.

**Comment by Braakie** [comment]
Exactly the same here, also the DCX960 living in the Netherlands. media_player.mediabox_next is not available
[home-assistant.log](https://github.com/Sholofly/lghorizon/files/14001431/home-assistant.log)

**Comment by deeg61** [comment]
This morning same here (Netherlands, ziggo box) no longer availlable

**Comment by golles** [comment]
`recording_capacity` sensor is working fine, only `media_player` remains unavailable

**Comment by golles** [comment]
Not sure if this is a HA core update issue, rolling back to `2024.1.4`, `2024.1.3` and `2024.1.2` doesn't make any difference

**Comment by JBakers** [comment]
> Not sure if this is a HA core update issue, rolling back to `2024.1.4`, `2024.1.3` and `2024.1.2` doesn't make any difference

yup, restoring previous backups results in same error, not available.

**Comment by JBakers** [comment]
> Exactly the same here, also the DCX960 living in the Netherlands. media_player.mediabox_next is not available [home-assistant.log](https://github.com/Sholofly/lghorizon/files/14000820/home-assistant.log)

looks like you uploaded my log (they're exactly the same)

**Comment by Braakie** [comment]
Sorry

> > Exactly the same here, also the DCX960 living in the Netherlands. media_player.mediabox_next is not available [home-assistant.log](https://github.com/Sholofly/lghorizon/files/14000820/home-assistant.log)
> 
> looks like you uploaded my log (they're exactly the same)

I was just comparing and seeing if I saw anything striking. Accidentally uploaded the wrong log. I fixed it and uploaded the correct log

**Comment by canedje** [comment]
same here
Netherlands: Next mini Ziggo after update HA core to 2024.1.5

**Comment by GHeiner** [comment]
I Have the same problem with my Next Mini Ziggo. After installing 2024.1.5 this morning the device the device stays unavailable. indeed the Recording percentage is available.

**Comment by Sholofly** [comment]
I can't reproduce the error myself, but i published a new version with a possible fix. Please try v0.5.5

**Comment by canedje** [comment]
It is up and running again after v0.5.5

**Comment by GHeiner** [comment]
Yes also in my case it's working as before

**Comment by Sholofly** [comment]
@nivula, Does it work in CH too?

**Comment by JBakers** [comment]
Confirmed working again. 0.5.5

**Comment by netrene** [comment]
0.5.5 does not fix it for me in Switzerland.

Logs ar still full with this:
2024-01-21 21:02:29.024 ERROR (SyncWorker_3) [lghorizon.lghorizon_api] Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-ch.gnp.cloud.sunrisetv.ch/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-prod-ch.gnp.cloud.sunrisetv.ch/auth-service/v1/mqtt/token)

**Comment by Braakie** [comment]
Thanks for the update, it works again.

**Comment by steuerzentrale** [comment]
> 0.5.5 does not fix it for me in Switzerland.
> 
> Logs ar still full with this: 2024-01-21 21:02:29.024 ERROR (SyncWorker_3) [lghorizon.lghorizon_api] Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-ch.gnp.cloud.sunrisetv.ch/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-prod-ch.gnp.cloud.sunrisetv.ch/auth-service/v1/mqtt/token)

can confirm that 0.5.5 does not work in Switzerland, I got exactly the same error.

Core 2024.1.5
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0

**Comment by DaveCamenisch** [comment]
Same here in Switzerland - 0.5.5 is not working!
Brand new installation on a rPi4. All updates done.

Core 2024.1.5
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0

Logger: lghorizon.lghorizon_api
Source: /usr/local/lib/python3.11/site-packages/backoff/_common.py:120
First occurred: 20:24:42 (31 occurrences)
Last logged: 21:39:10

Giving up connect(...) after 11 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-ch.gnp.cloud.sunrisetv.ch/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-prod-ch.gnp.cloud.sunrisetv.ch/auth-service/v1/mqtt/token)

**Comment by Sholofly** [comment]
I've published a new version. Please try if it works for you guys...

**Comment by steuerzentrale** [comment]
v 0.5.6 is not working either, got the following logs:

Logger: lghorizon.lghorizon_api
Source: /usr/local/lib/python3.11/site-packages/backoff/_common.py:120
First occurred: 22:43:13 (2 occurrences)
Last logged: 22:43:21

Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://prod.spark.sunrisetv.ch/v1/mqtt/token. Error:404 Client Error: Not Found for url: https://prod.spark.sunrisetv.ch/v1/mqtt/token)

**Comment by Sholofly** [comment]
Oops thats my bad. Give me a few minutes

**Comment by Sholofly** [comment]
@steuerzentrale Would you mind updating and try again?

**Comment by netrene** [comment]
@Sholofly 

0.5.7 does not fix the problem either in Switzerland.

File "/config/custom_components/lghorizon/__init__.py", line 50, in async_setup_entry
    await hass.async_add_executor_job(api.connect)
asyncio.exceptions.CancelledError: Global task timeout
2024-01-22 23:22:34.650 WARNING (MainThread) [homeassistant.bootstrap] Setup timed out for stage 2 - moving forward
2024-01-22 23:22:35.001 WARNING (MainThread) [homeassistant.components.homekit.type_remotes] media_player.upc: Reached maximum number of sources (90)
2024-01-22 23:24:16.531 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 0775274852 for lghorizon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lghorizon/__init__.py", line 50, in async_setup_entry
    await hass.async_add_executor_job(api.connect)
asyncio.exceptions.CancelledError

**Comment by DaveCamenisch** [comment]
No, unfortunately it does not work with 0.5.7 either... 

This error originated from a custom integration.

Logger: custom_components.lghorizon.config_flow
Source: custom_components/lghorizon/config_flow.py:58
Integration: LG Horizon (documentation, issues)
First occurred: 23:28:03 (2 occurrences)
Last logged: 23:40:38

'hashedCustomerId'


2024-01-22 23:28:03.847 ERROR (SyncWorker_4) [lghorizon.lghorizon_api] Giving up connect(...) after 11 tries (KeyError: 'hashedCustomerId')
2024-01-22 23:28:03.853 ERROR (MainThread) [custom_components.lghorizon.config_flow] 'hashedCustomerId'
2024-01-22 23:40:38.451 ERROR (SyncWorker_1) [lghorizon.lghorizon_api] Giving up connect(...) after 11 tries (KeyError: 'hashedCustomerId')
2024-01-22 23:40:38.455 ERROR (MainThread) [custom_components.lghorizon.config_flow] 'hashedCustomerId'

**Comment by JimmyKer** [comment]
Hi,

Same problem for me in Belgium, using Telenet. running version version 0.5.5 from the plugin.

I've managed in the last days to keep a working 'LG Horizon' integration by:

- After a HA reboot
- Downgrade 'LG Horizon' to version 0.5.3
- Upgrade to  'LG Horizon' to version 0.5.5
- Reload YAML configurations, although I'm not 100% this step is required. 
- Restart Home Assistant
- Now the integration works again.

Hope this helps other too :)

Kind regards,
Jimmy

**Comment by netrene** [comment]
@Sholofly 
Is there anything I an do to help you debug the problem in Switzerland?
Does a Wireshark log help you more than the internal HA logs. Let me know if I could do anything to support (also remote session possible).

Best Regards
René

**Comment by Sholofly** [comment]
@netrene Please try the latest version. If you still have the problem, please open a new issue. It's very specific for your country.

**Comment by netrene** [comment]
> @netrene Please try the latest version. If you still have the problem, please open a new issue. It's very specific for your country.

I tried 0.5.7 already and its not working. Or is there a newer version?

**Comment by Sholofly** [comment]
yes 0.5.8

**Comment by netrene** [comment]
> yes 0.5.8

I uninstalled the integration and rebooted. Then I installed 0.5.8 and voila it´s working again in Switzerland.

Thx for your effort.

René

**Comment by DaveCamenisch** [comment]
THANK YOU @Sholofly !! 😀👍🏼
